config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments do

    end
  end

  get 'welcome/about' => 'welcome#about'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  get '/users/:id' => 'users#show', as: :user

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  root 'welcome#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  belongs_to :user
  mount_uploader :picture, PictureUploader

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :comments
  has_many :posts
  def admin?
    self.role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :require_user, :require_admin

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    redirect_to '/login' unless current_user
  end

  def require_admin
    redirect_to '/login' unless current_user.admin?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user
  before_action :require_admin, only: [:destroy]

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to comment_path(@post)
  end

  private
    def comment_params
        params.require(:comment).permit(:body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_user, except: [:index, :show]
  def index
    @posts = Post.all
    @randompic= Post.offset(rand(Post.count)).first.picture.url
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to user_path(current_user.id)
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private
    def post_params
        params.require(:post).permit(:title, :picture, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to("/users/#{@user.id}")
    else
      flash[:error] = 'Incorrect Login'
      redirect_to('/login')
    end
  end

  def destroy
    session[:user_id]=nil
    redirect_to('/')
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to("/users/#{@user.id}")
    else
      redirect_to('/signup')
    end
  end
  def show
    @user = User.find(params[:id])
    @post = Post.new
    @posts=@user.posts
  end

  private
    def user_params
      params.require(:user).permit(:name,:email,:password,:password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  def about
      @posts = Post.all
      @randompic= Post.offset(rand(Post.count)).first.picture.url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
  <div class="comment-image">
    <img src="http://i.imgur.com/egYI57i.png" title="source: imgur.com" />
  </div>
  <div class="comment-content">
    <h4>Comment:</h4>
    <p><%= comment.body %></p>
    <p><%= link_to 'Destroy Comment', [comment.post, comment],
        method: :delete,
        data: { confirm: 'Are you sure?' } %>
    </p>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <div class="comment">
    <div class="comment-content">
      <h4><%= f.label :body %></h4>
      <p><%= f.text_area :body %></p>
      <p><%= f.submit %></p>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>VisualYou</title>
    <link href='https://fonts.googleapis.com/css?family=Monoton' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

    <%= yield %>
  <footer class="footer-2" role="contentinfo">
    <div class="footer-logo">
     <img src="https://i.imgur.com/egYI57i.png" title="source: imgur.com" />
    </div>
    <ul>
      <% if current_user %>
        <li class="nav-link">Signed in as <strong><%=current_user.name%></strong></li>
        <li class="nav-link"><%= link_to 'My Board', user_path(current_user) %></li>
        <li class="nav-link"><%= link_to "Logout", '/logout' %></li>
        <li class="nav-link"><%= link_to 'Take a look at other boards', controller: 'posts' %></li>
      <% elsif current_user && current_user.admin? %>
        <li>Signed in as Admin</li>
      <% else %>
        <li class="nav-link"><%= link_to "Login", login_path %></li>
        <li class="nav-link"><%= link_to "Signup", signup_path %></li>
        <li class="nav-link"><%= link_to 'Back', '/' %></li>
      <%end%>
    </ul>
  </footer>

</html>

app/views/posts/_form.html.erb
<%= form_for(@post, html: {multipart: true}) do |f| %>
  <div class='field'>
    <%= f.text_field :title, placeholder: "Create board..." %>
    <span>
      <%= f.file_field :picture%>
      <%= f.hidden_field :user_id, value: current_user.id %>
    </span>
    <%= f.submit "Board" %>
  </div>
<%end%>

app/views/posts/edit.html.erb
<h1> Edit Post </h1>
<%= render 'form' %>
<%= link_to 'Back', users_path %>

app/views/posts/index.html.erb
<div class="image-gradient-dynamic">
      <p><%= image_tag @randompic %></p>
</div>
<div class="grid-item-big">
  <img src="http://i.imgur.com/egYI57i.png" title="source: imgur.com" />
</div>

app/views/posts/new.html.erb
<h1>Post</h1>
<div>
<%= render 'form' %>
</div>
<%= link_to 'Back', users_path %>

app/views/posts/show.html.erb
<h1>Posts</h1>
<div>
  <div><%= @post.title %></div>
  <%= image_tag @post.picture.url %>
</div>
<div>
<%= render @post.comments %>
</div>
<div>
<%= render 'comments/form' %>
</div>

<%= link_to 'Edit', edit_post_path(@post) %>
<%= link_to 'Back', posts_path %>

app/views/users/_form.html.erb
<%= form_for(@post, html: {multipart: true}) do |f| %>
  <div class='field'>
    <%= f.text_field :title, placeholder: "Create board..." %>
    <span>
      <%= f.file_field :picture %>
      <%= f.hidden_field :user_id, value: current_user.id %>
    </span>
    <%= f.submit "Board" %>
  </div>
<%end%>

app/views/users/new.html.erb
<div class="main">
  <div class="container">
    <h1>Join Visual You</h1>
      <%= form_for(@user) do |f|%>
        <div class="form-group">
          <%=f.label :name %>
          <%= f.text_field :name, class: 'form-control'%>
        </div>
        <div class="form-group">
          <%=f.label :email %>
          <%= f.email_field :email, class: 'form-control'%>
        </div>
        <div class="form-group">
          <%=f.label :password %>
          <%= f.password_field :password, class: 'form-control'%>
        </div>
        <div class="form-group">
          <%=f.label :password_confirmation %>
          <%= f.password_field :password, class: 'form-control'%>
        </div>
        <%= f.submit"Create Account", class:'btn'%>
      <%end%>
  </div>
 </div>

app/views/users/show.html.erb
<div class="grid-items">
  <div class="grid-item grid-item-big"> <h1>Welcome <%= current_user.name %></h1></div>
  <div class="grid-item"><h1><%= link_to 'Create new', new_post_path %> Board </h1></div>
    <% @posts.each do |post| %>
    <div class="grid-item-image">
      <div>
        <%= post.title %>
        <%= image_tag post.picture.url if post.picture? %>
      </div>
      <%= link_to 'Show', post_path(post) %>
      <%= link_to 'Edit', edit_post_path(post) %>
      <% if current_user || current_user.admin? %>
        <%= link_to 'Destroy', post_path(post),
              method: :delete,
              data: {confirm: 'Are you sure?'} %>
      <%end%>
    </div>
    <% end %>
  </div>
</div>

app/views/welcome/about.html.erb
<div class="grid-items">
  <div class="grid-item">
    <h1>About </h1>
  </div>
  <div class="grid-item grid-item-big">
    <h1>Visual You</h1>
  </div>
  <div class="grid-item grid-item-big">
    <h1>Upload images.</h1>
  </div>
  <div class="grid-item">
    <h1>Save them.</h1>
  </div>
  <div class="grid-item">
    <img src="http://i.imgur.com/egYI57i.png" title="source: imgur.com" />
  </div>
  <div class="grid-item grid-item-big">
    <h1>Get Inspired!</h1>
  </div>
  <div class="grid-item-image ">
    <%= image_tag @randompic %>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="image-gradient-dynamic">
<img src="http://i.imgur.com/Q1vguAN.gif" title="source: imgur.com" />
  <div class="overlay"></div>
  <div class = 'copy'><p>What are we all <%= link_to 'About', welcome_about_path %></p></div>
</div>